[Fix]: Made GitHub buttons mobile responsive
vinitshahdeo/topmate-readme-badge pull request #47
Opened 2022-10-31 05:06 UTC by mani-rsg

This fixes issue #46 
Made the GitHub buttons in header to be mobile responsive.

<img width="399" alt="image" src="https://user-images.githubusercontent.com/72298612/198935191-8dcac840-b290-4da0-809d-852b18d21fbc.png">

2022-10-31 07:01 UTC, mani-rsg commented
Hi @vinitshahdeo , as today is the last day for hacktoberfest, can you please review and merge if it's fine?

2022-10-31 19:20 UTC, vinitshahdeo requested changes
Hey @mani-rsg 

Sorry for the late reply. The changes were required to center align the div of three GH icons in the same line.

2022-11-01 06:37 UTC, vinitshahdeo commented
Hey @mani-rsg 

I fixed this yesterday as I had the launch planned on Product hunt.

Please take a look: https://www.producthunt.com/posts/topmate-io-readme-badge-generator

2022-11-01 09:35 UTC, mani-rsg commented
Hey @vinitshahdeo ok no problem. BTW, Congrats on your launch

2022-11-03 01:38 UTC, closed without merging